### ISSUE TITLE
Type inference lens

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#14]
Selects the type of each attribute based on the majority of values in the record.  Allows for the possibility of errors in the type selection.

**Comment by Legacy25** [comment]
I have got the infrastructure for this to work. I am now working on the actual inference logic. It would be helpful to know what is/are the format(s) of date supported by SQL? I am working under the assumption that its just ```YYYY-MM-DD``` for now.

**Comment by Legacy25** [comment]
*supported by Mimir

**Comment by Legacy25** [comment]
A basic version of this is working. Types are inferred by pattern matching them against ints, floats, dates and booleans and collecting votes for matches. The type with the max votes wins if votes for that type is greater than 95% of the total votes, otherwise it defaults to String. Need a coercion policy for dealing with values that do not conform to the inferred type (the other 5%).

**Comment by okennedy** [comment]
Kickass.  Just replace non-conforming types with NULL values for now.

**Comment by Legacy25** [comment]
Done.

CSV imports now work with headers (no types, just attribute names), and type inference I think works (tested with just the Employee table in awesomedb, needs further testing).
