### ISSUE TITLE
Box for explanation of missing value lens result is not showing at all

### ISSUE THREAD

**Issue by sophieyoung717** [UBOdin/mimir#166]
When I ran Mimir, I replaced a null value resulting from a type inference lens (A3 in a numeric column is replaced with null), the estimation result showed, but the explanation box didn't show. Below is the process I did for product, rating1, rating2 tables.

1. load ratings1.csv, ratings2.csv    (rating cell with product id P2345 is A3)
2. Missing Value for rating1 in rating column. (rating with product id P2345 is 4 now)
3. click on 4, nothing showed.

**Comment by mrb24** [comment]
This bug appears to be fixed. Filtering by provenance of the above example gives:
PROJECT[PID <= CAST(PID, {{ LENS_TYPE_INFERENCE1979872127;0[][] }}), RATING <= IF CAST(RATING, {{ LENS_TYPE_INFERENCE1979872127;1[][] }}) IS NULL THEN IF  ({{ LENS_MISSING_VALUE1133189369:META:RATING;0[][] }}='WEKA')  THEN {{ LENS_MISSING_VALUE1133189369:WEKA:RATING;0[MIMIR_MAKE_ROWID(MIMIR_ROWID)][CAST(PID, {{ LENS_TYPE_INFERENCE1979872127;0[][] }}), CAST(RATING, {{ LENS_TYPE_INFERENCE1979872127;1[][] }}), CAST(REVIEW_CT, {{ LENS_TYPE_INFERENCE1979872127;2[][] }})] }} ELSE NULL END ELSE CAST(RATING, {{ LENS_TYPE_INFERENCE1979872127;1[][] }}) END, REVIEW_CT <= CAST(REVIEW_CT, {{ LENS_TYPE_INFERENCE1979872127;2[][] }}), MIMIR_ROWID_0 <= MIMIR_ROWID](
  SELECT[ (MIMIR_ROWID='2') ](
    RATINGS1_RAW(PID:varchar, RATING:varchar, REVIEW_CT:varchar // MIMIR_ROWID:rowid <- ROWID)
  )
)
as the operator filtered by provenance,  which results in the following when getting the focused reason of the explained subset for the above operator.

0.) I guessed that LENS_TYPE_INFERENCE1979872127.RATING was of type REAL because around 75% of the data fit {{LENS_TYPE_INFERENCE1979872127;1[]}}, 

1.) I defaulted to guessing with 'WEKA' (out of WEKA) for picking a value for column 'RATING' {{LENS_MISSING_VALUE1133189369:META:RATING;0[]}}, 

2.) I used a classifier to guess that LENS_MISSING_VALUE1133189369.RATING = 4.0 on row '2' (0.3333333333333333 out of 1.0 votes) {{LENS_MISSING_VALUE1133189369:WEKA:RATING;0['2']}}, 

3.) I guessed that LENS_TYPE_INFERENCE1979872127.RATING was of type REAL because around 75% of the data fit {{LENS_TYPE_INFERENCE1979872127;1[]}}

Though it does appear that reasons are duplicated (0 and 3 above) for queries over composed lenses.

**Comment by mrb24** [comment]
Explain subset now filters duplicate reasons.  commit: 8e48b5622da2fe792386c8a322257421c245515b
