### ISSUE TITLE
Parser issues with lens arguments 

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#46]
Can't have 0 arguments.
2 arguments seems to break things too.

**Comment by CodingSage** [comment]
The create schema matching lens statement was breaking because some of the changes were reverted. The parser doesn't accept any type arguments after the column names.
` CREATE LENS Matched AS SELECT * FROM RATINGS2 WITH SCHEMA_MATCHING (PID string, RATING float, REVIEW_CT float); `
Here, it threw an error on string after PID. I added the change back, it seems to be working for multiple or no arguments also. Could you please review my change?

**Comment by okennedy** [comment]
In principle, this is ok.  However, the changes should be applied to JSqlParserCC.jj and not the files generated by it. You can compile using `sbt parser`
