### ISSUE TITLE
Populate a default lens name in lens builder

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#52]
e.g., Type Inference on Ratings would have a default name Ratings_Typed

**Comment by Legacy25** [comment]
The cost to benefit ratio in populating a meaningful default name (ratings1_typed or ratings2_typed, instead of a random name) seems to be a bit off, since we would need a client-side sql parsing library to extract tables names or aliases of complex queries reliably. Should I go that route or just put in a default name that is not dependent on the query in any way?

**Comment by okennedy** [comment]
This could potentially be done server-side (e.g., by sending a suggested name for the query).  For now though, sure, provide this as a randomly assigned string.

**Comment by okennedy** [comment]
server side implementation complete as of c04186e7d9a842aa8db18656238044b80bdd22a9
